/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.sql.SQLException;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import persistencia_semdao.Produto;

/**
 *
 * @author alunocmc
 */
public class TelaProduto extends javax.swing.JFrame {

    /**
     * Creates new form TelaProduto
     */
    public TelaProduto() {
        initComponents();
        
        configurarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        consultartodosBtn = new javax.swing.JButton();
        mensagemLbl = new javax.swing.JLabel();
        mensagemTxt = new javax.swing.JTextField();
        idLbl = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        descricaoLbl = new javax.swing.JLabel();
        descricaoTxt = new javax.swing.JTextField();
        precoLbl = new javax.swing.JLabel();
        precoTxt = new javax.swing.JTextField();
        cadastrarBtn = new javax.swing.JButton();
        deletarBtn = new javax.swing.JButton();
        atualizarBtn = new javax.swing.JButton();
        gerenciarprotosLbl = new javax.swing.JLabel();
        pesquisaridBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaTbl = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        consultartodosBtn.setText("Consultar Todos");
        consultartodosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultartodosBtnActionPerformed(evt);
            }
        });

        mensagemLbl.setText("Mensagem:");

        idLbl.setText("ID:");

        descricaoLbl.setText("Descrição:");

        descricaoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descricaoTxtActionPerformed(evt);
            }
        });

        precoLbl.setText("Preço:");

        precoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precoTxtActionPerformed(evt);
            }
        });

        cadastrarBtn.setText("Cadastrar");
        cadastrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarBtnActionPerformed(evt);
            }
        });

        deletarBtn.setText("Deletar");
        deletarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarBtnActionPerformed(evt);
            }
        });

        atualizarBtn.setText("Atualizar");
        atualizarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarBtnActionPerformed(evt);
            }
        });

        gerenciarprotosLbl.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        gerenciarprotosLbl.setText("Gerenciar Produtos");

        pesquisaridBtn.setText("Pesquisar por ID");
        pesquisaridBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisaridBtnActionPerformed(evt);
            }
        });

        tabelaTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Descrição", "Preço"
            }
        ));
        tabelaTbl.setToolTipText("");
        jScrollPane2.setViewportView(tabelaTbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(precoLbl)
                            .addComponent(descricaoLbl)
                            .addComponent(idLbl)
                            .addComponent(mensagemLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(precoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pesquisaridBtn))
                            .addComponent(descricaoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mensagemTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gerenciarprotosLbl)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cadastrarBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deletarBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(atualizarBtn)
                        .addGap(92, 92, 92)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(consultartodosBtn)
                        .addGap(0, 133, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {idTxt, precoTxt});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(gerenciarprotosLbl)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idLbl)
                            .addComponent(pesquisaridBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(descricaoLbl)
                            .addComponent(descricaoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(precoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(precoLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mensagemTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mensagemLbl)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastrarBtn)
                    .addComponent(deletarBtn)
                    .addComponent(atualizarBtn)
                    .addComponent(consultartodosBtn))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {descricaoTxt, idTxt, mensagemTxt, precoTxt});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {atualizarBtn, consultartodosBtn});

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Produto p = new Produto();
    
    private void configurarTabela() {
    //Evita que o Swing redimensione automaticamente
    tabelaTbl.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

    //Ajusta largura das colunas
    tabelaTbl.getColumnModel().getColumn(0).setPreferredWidth(25);   // ID
    tabelaTbl.getColumnModel().getColumn(1).setPreferredWidth(150);  // Descrição
    tabelaTbl.getColumnModel().getColumn(2).setPreferredWidth(55);   // Preço
    }
    
    private void consultartodosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultartodosBtnActionPerformed
        // TODO add your handling code here:
        try {
            List<Produto> lprod = p.consultarTodos();

            //Define colunas
            String[] colunas = {"ID", "Descrição", "Preço"};
            DefaultTableModel modelo = new DefaultTableModel(colunas, 0);

            // Adiciona cada produto como uma linha
            for (Produto prod : lprod) {
                Object[] linha = {
                    prod.getId(),
                    prod.getDescricao(),
                    prod.getPreco()
                };
                modelo.addRow(linha);
            }

            //Atualiza a tabela
            tabelaTbl.setModel(modelo);
            tabelaTbl.getColumnModel().getColumn(0).setPreferredWidth(25);   // ID
            tabelaTbl.getColumnModel().getColumn(1).setPreferredWidth(150);  // Descrição
            tabelaTbl.getColumnModel().getColumn(2).setPreferredWidth(55);   // Preço
            
            } catch (SQLException | ClassNotFoundException ex) {
                mensagemTxt.setText("Erro: " + ex.getMessage());
            } catch (Exception ex) {
                mensagemTxt.setText("Erro inesperado: " + ex.getMessage());
            }       
    }//GEN-LAST:event_consultartodosBtnActionPerformed

    private void descricaoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descricaoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descricaoTxtActionPerformed

    
    private void cadastrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarBtnActionPerformed
        // TODO add your handling code here:
        try {
            //Valida descrição
            String descricao = descricaoTxt.getText();
            if (descricaoTxt == null || descricao.trim().isEmpty()){
                mensagemTxt.setText("Erro: a descrição não pode estar vazia");
                return;
            }
            
            //Valida preço
            String precoStr = precoTxt.getText();
            if (precoStr == null || precoStr.trim().isEmpty()) {
                mensagemTxt.setText("Erro: o preço não pode estar vazio");
                return;
            }
        
            //Cadastra o produto
            String upDescricaoTxt = descricaoTxt.getText().toUpperCase();
            p.setDescricao(upDescricaoTxt);
            p.setPreco(Double.parseDouble(precoTxt.getText()));
            p.cadastrar();
            
            mensagemTxt.setText("");
            mensagemTxt.setText("Cadastrado com sucesso");
            
        //Exceptions
        } catch (SQLException | ClassNotFoundException ex) {
            mensagemTxt.setText("");
            
            mensagemTxt.setText("Erro: " + ex.getMessage());
        } catch (NumberFormatException ex){
            mensagemTxt.setText("");
            mensagemTxt.setText("Erro: Preço inválido.");
        } catch (Exception ex) {
            mensagemTxt.setText("Erro inesperado: " + ex.getMessage()); //Erros inesperados
        }
    }//GEN-LAST:event_cadastrarBtnActionPerformed

    private void deletarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarBtnActionPerformed
        // TODO add your handling code here:
        try{
            //Deleta o produto
            p.setId(Integer.parseInt(idTxt.getText()));
            boolean deletado = p.deletar();
            //Limpa os campos dos textos
            descricaoTxt.setText("");
            precoTxt.setText("");
            mensagemTxt.setText("");
            
            //Verifica se foi deletado
            
            if (deletado) {
                mensagemTxt.setText("Deletado com sucesso");
            } else {
                mensagemTxt.setText("ID não encontrado. Nenhum registro foi deletado.");
            }
            
        //Exceptions
        }catch(SQLException | ClassNotFoundException ex){
            //Limpa campos
            mensagemTxt.setText("");
            
            mensagemTxt.setText("Erro: " + ex.getMessage());
        } catch (NumberFormatException ex){
            //Limpa campos
            mensagemTxt.setText("");
            mensagemTxt.setText("Erro: ID inválido.");
        } catch (Exception ex) {
            mensagemTxt.setText("Erro inesperado: " + ex.getMessage()); //Erros inesperados
        }
    }//GEN-LAST:event_deletarBtnActionPerformed

    private void atualizarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarBtnActionPerformed
        // TODO add your handling code here:
        try {
            //Atualiza um produto
            p.setId(Integer.parseInt(idTxt.getText()));
            String upDescricaoTxt = descricaoTxt.getText().toUpperCase();
            p.setDescricao(upDescricaoTxt);
            p.setPreco(Double.parseDouble(precoTxt.getText()));
            
            //Verifica se a descrição está vazia
            String descricao = descricaoTxt.getText();
            if (descricaoTxt == null || descricao.trim().isEmpty()){
                mensagemTxt.setText("Erro: a descrição não pode estar vazia");
                return;
            }
            p.atualizar();
            
            //Limpa o campo de texto da mensagem
            mensagemTxt.setText("");
            
            //verifica se algo foi atualizado
            boolean atualizado = p.atualizar();
            if (atualizado) {
                mensagemTxt.setText("Atualizado com sucesso");
            } else {
                mensagemTxt.setText("ID não encontrado. Nenhum registro foi atualizado.");
            }
        
        //Exeptions
        } catch (SQLException | ClassNotFoundException ex) {
            //Limpa campos
            mensagemTxt.setText("");
            mensagemTxt.setText("Erro: " + ex.getMessage());
        } catch (NumberFormatException ex){
            //Limpa campos
            mensagemTxt.setText("");
            mensagemTxt.setText("Erro: Preço inválido.");
        } catch (Exception ex) {
            mensagemTxt.setText("Erro inesperado: " + ex.getMessage()); //Erros inesperados
        }
    }//GEN-LAST:event_atualizarBtnActionPerformed

    private void precoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precoTxtActionPerformed

    private void pesquisaridBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisaridBtnActionPerformed
        // TODO add your handling code here:
        try {
            //Pega o id e busca o produto
            p.setId(Integer.parseInt(idTxt.getText()));
            p = p.consultarById();
            
            //verifica se o id é válido
            if (p != null && p.getId() > 0) {
                //Limpa os campos de texto
                idTxt.setText("");
                descricaoTxt.setText("");
                precoTxt.setText("");
                
                //traz as informações
                idTxt.setText(""+p.getId());
                descricaoTxt.setText("" + p.getDescricao());
                precoTxt.setText("" + p.getPreco());
            }else { //Caso não encontre
                //Limpa campos
                descricaoTxt.setText("");
                precoTxt.setText("");
                
                mensagemTxt.setText("ID não encontrado.");
            }
            
        //Exceptions
        } catch (SQLException | ClassNotFoundException ex) {
            mensagemTxt.setText("Erro: " + ex.getMessage());
        }catch (NumberFormatException ex) {
            mensagemTxt.setText("ID inválido. Digite um número.");
        } catch (Exception ex) {
            mensagemTxt.setText("Erro inesperado: " + ex.getMessage()); //Erros inesperados
        }
    }//GEN-LAST:event_pesquisaridBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizarBtn;
    private javax.swing.JButton cadastrarBtn;
    private javax.swing.JButton consultartodosBtn;
    private javax.swing.JButton deletarBtn;
    private javax.swing.JLabel descricaoLbl;
    private javax.swing.JTextField descricaoTxt;
    private javax.swing.JLabel gerenciarprotosLbl;
    private javax.swing.JLabel idLbl;
    private javax.swing.JTextField idTxt;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel mensagemLbl;
    private javax.swing.JTextField mensagemTxt;
    private javax.swing.JButton pesquisaridBtn;
    private javax.swing.JLabel precoLbl;
    private javax.swing.JTextField precoTxt;
    private javax.swing.JTable tabelaTbl;
    // End of variables declaration//GEN-END:variables
}
